import {expect,test} from 'bun:test';
import {digest} from '../src/hub/node.js';
import {createApp} from '../src/http.js';
import {CarriageQuotes} from '../src/hub/carriage-quote.js';
import {DeliveryRegister} from '../src/hub/delivery.js';
import {ApprovalDesk} from '../src/hub/approval.js';
import {RecoveryRegister} from '../src/hub/node.js';
import {PermissionLedger} from '../src/hub/permissions.js';
import {Registry} from '../src/shared/registry.js';
import {makeEngine,HOUSEHOLD,MANDATE,CONFIG_VERSION,HOUR,decideSigned} from './helpers.js';
function host(){const {engine}=makeEngine();const quotes=new CarriageQuotes();const app=createApp(engine,{quotes,deliveries:new DeliveryRegister(),approvals:new ApprovalDesk(),recovery:new RecoveryRegister(),permissions:new PermissionLedger(),registry:new Registry()});return {engine,quotes,app};}
const path=`https://unit.example/households/${encodeURIComponent(HOUSEHOLD)}`;
const archive=async(h:ReturnType<typeof host>)=>(await h.app(new Request(path+'/export'))).json() as Promise<any>;
const move=(h:ReturnType<typeof host>,node:unknown)=>h.app(new Request(path+'/import',{method:'POST',body:JSON.stringify(node)}));
async function source(settled=true){const h=host(),now=Date.now();const offer=h.engine.createOffer({binding:'digital',household:HOUSEHOLD,purpose:'replenish',config_version:CONFIG_VERSION,expires_at:now+HOUR,mandate:MANDATE,price_band:null,giver:null,candidates:[{product:'tea-a',quantity:1,predicted_conversion:0.5,is_exploration:true,given_by:null}]} as never);h.quotes.record(offer.id,550,now);await h.engine.present(offer.id,now);if(settled){await decideSigned(h.engine,offer.id,h.engine.mustGet(offer.id,now).candidates.map(c=>({candidate:c.id,valence:'kept',kept_as:'self'})));await h.engine.settle(offer.id,now);}return {...h,offer};}
test('quotation and retained protections survive a household move and identical retry',async()=>{const a=await source(),node=await archive(a),b=host();expect(node.format).toBe('valence-node/12');expect(node.carriage_quotes).toEqual([a.quotes.find(a.offer.id)]);expect((await move(b,node)).status).toBe(201);expect(b.quotes.find(a.offer.id)).toEqual(a.quotes.find(a.offer.id));expect((await archive(b)).decided_protections).toEqual(node.decided_protections);expect((await archive(b)).confirmations).toEqual(node.confirmations);expect((await move(b,node)).status).toBe(201);});
test('unfinished offer and its quote remain at source',async()=>{const a=await source(false),b=host();const response=await move(b,await archive(a));expect(response.status).toBe(201);expect((await response.json() as any).left_behind).toContain(a.offer.id);expect(b.quotes.find(a.offer.id)).toBeUndefined();expect((await archive(b)).offers).toEqual([]);});
test('unscoped malformed duplicate and changed quotes refuse before importing offers',async()=>{const a=await source(),node=await archive(a);for(const mutate of [(n:any)=>n.carriage_quotes[0].offer='foreign',(n:any)=>n.carriage_quotes[0].carriage=-1,(n:any)=>n.carriage_quotes[0].quoted_at=0.5,(n:any)=>n.carriage_quotes.push({...n.carriage_quotes[0]}),(n:any)=>n.carriage_quotes[0].extra=true,(n:any)=>delete n.carriage_quotes]){const b=host(),changed=structuredClone(node);mutate(changed);expect((await move(b,changed)).status).toBeGreaterThanOrEqual(400);expect((await archive(b)).offers).toEqual([]);}});
test('reimport cannot replace a quote or append one to a legacy carried offer',async()=>{const a=await source(),node=await archive(a),b=host();expect((await move(b,node)).status).toBe(201);for(const key of ['carriage','quoted_at']){const changed=structuredClone(node);changed.carriage_quotes[0][key]++;expect((await move(b,changed)).status).toBeGreaterThanOrEqual(400);}expect(b.quotes.find(a.offer.id)).toEqual(a.quotes.find(a.offer.id));const c=host(),legacy=structuredClone(node);legacy.format='valence-node/8';delete legacy.carriage_quotes;expect((await move(c,legacy)).status).toBe(201);expect((await move(c,node)).status).toBe(409);expect(c.quotes.find(a.offer.id)).toBeUndefined();});
test('a storage failure at the quotation write rolls back the whole import',async()=>{const a=await source(),node=await archive(a),b=host();b.quotes.importRows=()=>{throw new Error('simulated disk failure');};expect((await move(b,node)).status).toBe(500);expect((await archive(b)).offers).toEqual([]);expect((await archive(b)).confirmations).toEqual({});expect((await archive(b)).decided_protections).toEqual({});});

test("archive digest includes quotations and retained protections but ignores export time",async()=>{const a=await source(),node=await archive(a),changed=structuredClone(node);changed.exported_at++;expect(digest(changed)).toBe(digest(node));changed.carriage_quotes[0].carriage++;expect(digest(changed)).not.toBe(digest(node));const protection=structuredClone(node);protection.decided_protections={};expect(digest(protection)).not.toBe(digest(node));});
